-- Cyber-shot T/TX sourcing app schema
-- Run this in Supabase SQL Editor.

create table if not exists public.model_market_metrics (
  model text primary key,
  series text not null,
  avg_usd numeric not null,
  low_usd numeric not null,
  high_usd numeric not null,
  avg_shipping_usd numeric default 0,
  avg_free_shipping_total_usd numeric,
  free_shipping_count integer default 0,
  avg_paid_shipping_total_usd numeric,
  paid_shipping_count integer default 0,
  sell_through numeric default 0,
  listings integer default 0,
  reliability text default 'Unknown',
  rank text default 'D',
  source text default 'manual',
  updated_at timestamptz not null default now()
);

alter table public.model_market_metrics
  add column if not exists avg_free_shipping_total_usd numeric,
  add column if not exists free_shipping_count integer default 0,
  add column if not exists avg_paid_shipping_total_usd numeric,
  add column if not exists paid_shipping_count integer default 0;

create table if not exists public.market_snapshots (
  id bigint generated by default as identity primary key,
  model text not null references public.model_market_metrics(model) on delete cascade,
  sold_at timestamptz,
  title text,
  price_usd numeric,
  shipping_usd numeric,
  condition text,
  item_url text,
  source text default 'apify',
  captured_at timestamptz not null default now()
);

create table if not exists public.refresh_runs (
  id bigint generated by default as identity primary key,
  provider text not null default 'apify',
  status text not null default 'queued',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  models_count integer default 0,
  items_count integer default 0,
  note text
);

alter table public.model_market_metrics enable row level security;
alter table public.market_snapshots enable row level security;
alter table public.refresh_runs enable row level security;

drop policy if exists "public read model metrics" on public.model_market_metrics;
create policy "public read model metrics"
on public.model_market_metrics for select
to anon
using (true);

drop policy if exists "public read refresh runs" on public.refresh_runs;
create policy "public read refresh runs"
on public.refresh_runs for select
to anon
using (true);

-- Do not create anon insert/update policies.
-- Apify should write with the service_role key stored only in Apify secrets/environment variables.

insert into public.model_market_metrics
  (model, series, avg_usd, low_usd, high_usd, avg_shipping_usd, sell_through, listings, reliability, rank, source, updated_at)
values
  ('T1','T',148.22,90,510,24.2,0.3276,160,'High','S','seed',now()),
  ('T2','T',115.31,89.09,133,17.72,0.1058,27,'Medium','B','seed',now()),
  ('T11','T',112.15,85,139.3,12,0,2,'Low','D','seed',now()),
  ('T5','T',101.83,80,192,9.8,0,19,'Low','D','seed',now()),
  ('T7','T',112.4,80,225.5,10.76,0.1759,34,'Medium','A','seed',now()),
  ('T33','T',80,80,80,11.8,0.0078,1,'Low','D','seed',now()),
  ('T9','T',106.54,80,199.99,11.37,0.0337,13,'Low','C','seed',now()),
  ('T10','T',120.69,81,163,12.35,0.0913,55,'Medium','B','seed',now()),
  ('T30','T',100.27,85,121,14.19,0.0474,10,'Low','C','seed',now()),
  ('T50','T',130.99,80,400,10.61,0.0511,9,'Low','C','seed',now()),
  ('T20','T',118.65,80,178.5,12.45,0.0575,25,'Medium','C','seed',now()),
  ('T70','T',128.83,80,349.4,16.27,0.1142,64,'Medium','B','seed',now()),
  ('T100','T',109.78,81,155,11.13,0.194,58,'High','A','seed',now()),
  ('T200','T',127.09,85,198.79,12.99,0.163,50,'High','A','seed',now()),
  ('T77','T',131.34,80,199,26.29,0.1752,102,'High','A','seed',now()),
  ('T300','T',110.62,80,199,10.33,0.087,20,'Medium','B','seed',now()),
  ('T500','T',136.96,99.95,168.99,12.5,0.0833,4,'Low','D','seed',now()),
  ('T700','T',148.22,90,510,24.2,0.3276,160,'High','S','seed',now()),
  ('T90','T',124.78,80,199,13.69,0.1855,80,'High','A','seed',now()),
  ('T900','T',129.58,85,399,17.74,0.1618,46,'Medium','A','seed',now()),
  ('TX1','TX',121.59,80,203,16.14,0.2186,85,'High','A','seed',now()),
  ('TX5','TX',122.93,83.3,165,15.27,0.0735,19,'Low','C','seed',now()),
  ('TX7','TX',120.9,89,172.5,11.13,0.1816,51,'High','A','seed',now()),
  ('TX9','TX',132.47,88,199.99,10.78,0.1514,28,'Medium','B','seed',now()),
  ('TX10','TX',131.25,85,176.6,16.96,0.1619,72,'High','A','seed',now()),
  ('TX55','TX',141.6,80,181.58,10.46,0.185,29,'Medium','B','seed',now()),
  ('TX100V','TX',133.84,107.99,180,34.85,0.1556,7,'Low','C','seed',now()),
  ('TX20','TX',140.05,80.99,186.33,14.22,0.2745,36,'Medium','A','seed',now()),
  ('TX66','TX',159.73,99.99,450,17.35,0.192,29,'Medium','B','seed',now()),
  ('TX200V','TX',148.74,119.99,175,9.62,0.8,4,'Low','D','seed',now()),
  ('TX30','TX',169.46,99,405,15.55,0.3789,55,'High','S','seed',now()),
  ('TX300V','TX',146.57,109.99,183.15,42,0.0556,2,'Low','D','seed',now())
on conflict (model) do update set
  series = excluded.series,
  avg_usd = excluded.avg_usd,
  low_usd = excluded.low_usd,
  high_usd = excluded.high_usd,
  avg_shipping_usd = excluded.avg_shipping_usd,
  sell_through = excluded.sell_through,
  listings = excluded.listings,
  reliability = excluded.reliability,
  rank = excluded.rank,
  source = excluded.source,
  updated_at = excluded.updated_at;
